import { Endpoint, Rule, RequestLog } from '@/app/types';

export const sampleEndpoints: Endpoint[] = [
  {
    id: 'ep_1',
    name: 'Get Users',
    method: 'GET',
    path: '/api/users',
    enabled: true,
    tags: ['users', 'list'],
    createdAt: '2026-01-14T10:00:00Z',
    updatedAt: '2026-01-14T10:00:00Z',
  },
  {
    id: 'ep_2',
    name: 'Get User By ID',
    method: 'GET',
    path: '/api/users/:id',
    enabled: true,
    tags: ['users', 'detail'],
    createdAt: '2026-01-14T10:05:00Z',
    updatedAt: '2026-01-14T10:05:00Z',
  },
  {
    id: 'ep_3',
    name: 'Create User',
    method: 'POST',
    path: '/api/users',
    enabled: true,
    tags: ['users', 'create'],
    createdAt: '2026-01-14T10:10:00Z',
    updatedAt: '2026-01-14T10:10:00Z',
  },
  {
    id: 'ep_4',
    name: 'Login',
    method: 'POST',
    path: '/api/auth/login',
    enabled: true,
    tags: ['auth'],
    createdAt: '2026-01-14T10:15:00Z',
    updatedAt: '2026-01-14T10:15:00Z',
  },
];

export const sampleRules: Rule[] = [
  {
    id: 'rule_1',
    endpointId: 'ep_1',
    name: 'Admin Users Only',
    priority: 0,
    enabled: true,
    conditions: [
      {
        type: 'query',
        key: 'role',
        operator: 'equals',
        value: 'admin',
      },
    ],
    responseStatus: 200,
    responseHeaders: {
      'Content-Type': 'application/json',
      'X-Total-Count': '2',
    },
    responseBody: JSON.stringify({
      users: [
        { id: 1, name: 'Admin User', email: 'admin@example.com', role: 'admin' },
        { id: 2, name: 'Super Admin', email: 'super@example.com', role: 'admin' },
      ],
    }, null, 2),
    delayMs: 100,
    createdAt: '2026-01-14T10:20:00Z',
    updatedAt: '2026-01-14T10:20:00Z',
  },
  {
    id: 'rule_2',
    endpointId: 'ep_1',
    name: 'All Users',
    priority: 10,
    enabled: true,
    conditions: [],
    responseStatus: 200,
    responseHeaders: {
      'Content-Type': 'application/json',
      'X-Total-Count': '5',
    },
    responseBody: JSON.stringify({
      users: [
        { id: 1, name: 'Alice Johnson', email: 'alice@example.com', role: 'user' },
        { id: 2, name: 'Bob Smith', email: 'bob@example.com', role: 'user' },
        { id: 3, name: 'Carol White', email: 'carol@example.com', role: 'user' },
        { id: 4, name: 'David Brown', email: 'david@example.com', role: 'moderator' },
        { id: 5, name: 'Eve Davis', email: 'eve@example.com', role: 'user' },
      ],
    }, null, 2),
    delayMs: 200,
    createdAt: '2026-01-14T10:25:00Z',
    updatedAt: '2026-01-14T10:25:00Z',
  },
  {
    id: 'rule_3',
    endpointId: 'ep_2',
    name: 'User Not Found',
    priority: 0,
    enabled: true,
    conditions: [
      {
        type: 'query',
        key: 'id',
        operator: 'equals',
        value: '999',
      },
    ],
    responseStatus: 404,
    responseHeaders: {
      'Content-Type': 'application/json',
    },
    responseBody: JSON.stringify({
      error: 'User not found',
      code: 'USER_NOT_FOUND',
    }, null, 2),
    delayMs: 50,
    createdAt: '2026-01-14T10:30:00Z',
    updatedAt: '2026-01-14T10:30:00Z',
  },
  {
    id: 'rule_4',
    endpointId: 'ep_2',
    name: 'User Found',
    priority: 10,
    enabled: true,
    conditions: [],
    responseStatus: 200,
    responseHeaders: {
      'Content-Type': 'application/json',
    },
    responseBody: JSON.stringify({
      id: 1,
      name: 'Alice Johnson',
      email: 'alice@example.com',
      role: 'user',
      createdAt: '2026-01-01T00:00:00Z',
    }, null, 2),
    delayMs: 100,
    createdAt: '2026-01-14T10:35:00Z',
    updatedAt: '2026-01-14T10:35:00Z',
  },
  {
    id: 'rule_5',
    endpointId: 'ep_3',
    name: 'Email Already Exists',
    priority: 0,
    enabled: true,
    conditions: [
      {
        type: 'body',
        key: 'email',
        operator: 'equals',
        value: 'existing@example.com',
      },
    ],
    responseStatus: 409,
    responseHeaders: {
      'Content-Type': 'application/json',
    },
    responseBody: JSON.stringify({
      error: 'Email already exists',
      code: 'EMAIL_CONFLICT',
    }, null, 2),
    delayMs: 50,
    createdAt: '2026-01-14T10:40:00Z',
    updatedAt: '2026-01-14T10:40:00Z',
  },
  {
    id: 'rule_6',
    endpointId: 'ep_3',
    name: 'User Created Successfully',
    priority: 10,
    enabled: true,
    conditions: [],
    responseStatus: 201,
    responseHeaders: {
      'Content-Type': 'application/json',
      'Location': '/api/users/6',
    },
    responseBody: JSON.stringify({
      id: 6,
      name: 'New User',
      email: 'newuser@example.com',
      role: 'user',
      createdAt: new Date().toISOString(),
    }, null, 2),
    delayMs: 150,
    createdAt: '2026-01-14T10:45:00Z',
    updatedAt: '2026-01-14T10:45:00Z',
  },
  {
    id: 'rule_7',
    endpointId: 'ep_4',
    name: 'Invalid Credentials',
    priority: 0,
    enabled: true,
    conditions: [
      {
        type: 'body',
        key: 'password',
        operator: 'equals',
        value: 'wrong',
      },
    ],
    responseStatus: 401,
    responseHeaders: {
      'Content-Type': 'application/json',
    },
    responseBody: JSON.stringify({
      error: 'Invalid credentials',
      code: 'INVALID_CREDENTIALS',
    }, null, 2),
    delayMs: 300,
    createdAt: '2026-01-14T10:50:00Z',
    updatedAt: '2026-01-14T10:50:00Z',
  },
  {
    id: 'rule_8',
    endpointId: 'ep_4',
    name: 'Login Success',
    priority: 10,
    enabled: true,
    conditions: [],
    responseStatus: 200,
    responseHeaders: {
      'Content-Type': 'application/json',
    },
    responseBody: JSON.stringify({
      token: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...',
      user: {
        id: 1,
        name: 'Alice Johnson',
        email: 'alice@example.com',
        role: 'user',
      },
      expiresIn: 3600,
    }, null, 2),
    delayMs: 200,
    createdAt: '2026-01-14T10:55:00Z',
    updatedAt: '2026-01-14T10:55:00Z',
  },
];

export const sampleLogs: RequestLog[] = [
  {
    id: 'log_1',
    timestamp: new Date(Date.now() - 120000).toISOString(),
    method: 'GET',
    path: '/api/users',
    query: { role: 'admin' },
    headers: { 'Content-Type': 'application/json' },
    matchedRuleId: 'rule_1',
    responseStatus: 200,
    responseTimeMs: 105,
  },
  {
    id: 'log_2',
    timestamp: new Date(Date.now() - 90000).toISOString(),
    method: 'GET',
    path: '/api/users/1',
    headers: { 'Content-Type': 'application/json' },
    matchedRuleId: 'rule_4',
    responseStatus: 200,
    responseTimeMs: 98,
  },
  {
    id: 'log_3',
    timestamp: new Date(Date.now() - 60000).toISOString(),
    method: 'POST',
    path: '/api/auth/login',
    headers: { 'Content-Type': 'application/json' },
    body: '{"email": "alice@example.com", "password": "wrong"}',
    matchedRuleId: 'rule_7',
    responseStatus: 401,
    responseTimeMs: 302,
  },
  {
    id: 'log_4',
    timestamp: new Date(Date.now() - 30000).toISOString(),
    method: 'POST',
    path: '/api/auth/login',
    headers: { 'Content-Type': 'application/json' },
    body: '{"email": "alice@example.com", "password": "correct"}',
    matchedRuleId: 'rule_8',
    responseStatus: 200,
    responseTimeMs: 198,
  },
  {
    id: 'log_5',
    timestamp: new Date(Date.now() - 10000).toISOString(),
    method: 'GET',
    path: '/api/users',
    headers: { 'Content-Type': 'application/json' },
    matchedRuleId: 'rule_2',
    responseStatus: 200,
    responseTimeMs: 203,
  },
];
